# Generated by Django 5.0.6 on 2024-06-26 06:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
                ("device", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("browser", models.CharField(max_length=100)),
                ("route", models.CharField(max_length=200)),
                ("access_time", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Consultant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.IntegerField(unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Консультант",
                "verbose_name_plural": "Консультанты",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("number", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_progress", "In progress"),
                            ("served", "Served"),
                            ("timeout", "Time Out"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ochered_app.consultant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Талон",
                "verbose_name_plural": "Талоны",
            },
        ),
    ]
