# Generated by Django 5.0.6 on 2024-06-07 11:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ochered_app', '0002_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
