# Generated by Django 5.0.6 on 2024-06-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ochered_app', '0003_alter_ticket_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultant',
            options={'verbose_name': 'Консультант', 'verbose_name_plural': 'Консультанты'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Талон', 'verbose_name_plural': 'Талоны'},
        ),
    ]
