# Generated by Django 5.0.2 on 2024-03-20 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=100)),
                ("device", models.CharField(max_length=100)),
                ("os", models.CharField(max_length=100)),
                ("browser", models.CharField(max_length=100)),
                ("route", models.CharField(max_length=200)),
                ("access_time", models.DateTimeField()),
            ],
        ),
    ]
